name: Check Slot Availability

on:
  schedule:
    - cron: '0 * * * *'  # Run every 60 minutes
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script
      run: bash check-slots.sh

